#server:
#  port: 10866

app:
  id: gc-framework
apollo:
  meta: http://127.0.0.1:8080  # 此处 连接的是 apollo-configservice 项目的端口地址
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

logging:
  level:
    com:
      allen: debug